### PR TITLE
Finish calculating depths of clusters and save them in near_planes

### PR DESCRIPTION
**Pull request by Phantomape**

### CODE REVIEW

**Comment by gongminmin** [comment]
The near_planes must be used in a revert way. Knowning how many depth slices we want, calculating the values of the near planes.

**Comment by Phantomape** [comment]
Change the calculations of near_planes accordingly

**Comment by gongminmin** [comment]
If you change the depth_slices_ to 4, you need to change the NUM_DEPTH_SLICES in fxml to 4, too. After that, the depth_slices become 5 floats. I suggest change the near planes calculation to:

```
float const near_plane = camera->NearPlane();
float const far_plane = camera->FarPlane();
float const base = far_plane / near_plane;
depth_slices[0] = near_plane;
for (uint32_t i = 1; i < num_depth_slices_; ++ i)
{
	depth_slices[i] = near_plane * pow(base, static_cast<float>(i) / num_depth_slices_);
}
depth_slices[num_depth_slices_] = far_plane;
```

depth_slices[0] is always near plane, depth_slices[num_depth_slices_] is always far plane. We just need to calculate the rests.

**Comment by gongminmin** [comment]
Looks in a good shape.

You need a extra vector in struct Cluster, to record the starts of each type of available lights. Same as lights_start_rw_tex in ClusteredDRLightIntersectionCS.

One more coding change: in OverlapTestSpot, add one more tab before std::vector<float3> const & lights_aabb_min.

**Pull request merged**
